export const endpoints = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    changePassword: '/auth/change-password',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  clients: {
    list: '/clients',
    search: '/clients/search',
    searchBranches: '/clients/branches/search',
    byId: (id: string) => `/clients/${id}`,
    detail: (id: string) => `/clients/${id}/detail`,
    create: '/clients',
    addBusiness: (clientId: string) => `/clients/${clientId}/businesses`,
    updateBusiness: (businessId: string) => `/clients/businesses/${businessId}`,
    addBranch: (businessId: string) => `/clients/businesses/${businessId}/branches`,
    updateBranch: (branchId: string) => `/clients/branches/${branchId}`,
    updateBranchCycle: (branchId: string) => `/clients/branches/${branchId}/cycle`,
    updateBranchConfiguration: (branchId: string) => `/clients/branches/${branchId}/configuration`,
    branchHistory: (branchId: string) => `/clients/branches/${branchId}/history`,
  },
  services: {
    create: '/services',
    byId: (id: string) => `/services/${id}`,
    day: '/services/day',
    month: '/services/month',
    upcoming: '/services/upcoming',
    technicianSchedule: (technicianId: string) => `/services/technician/${technicianId}/schedule`,
    updateStatus: (id: string) => `/services/${id}/status`,
    reschedule: (id: string) => `/services/${id}/reschedule`,
    cancel: (id: string) => `/services/${id}/cancel`,
    assignTechnicians: (id: string) => `/services/${id}/technicians`,
    start: (id: string) => `/services/${id}/start`,
    complete: (id: string) => `/services/${id}/complete`,
    notes: (id: string) => `/services/${id}/notes`,
    payment: (id: string) => `/services/${id}/payment`,
    paymentProof: (id: string) => `/services/${id}/payment-proof`,
    evidences: (id: string) => `/services/${id}/evidences`,
    generateReinforcement: (id: string) => `/services/${id}/generate-reinforcement`,
  },
  users: {
    create: '/users',
    list: '/users',
    technicians: '/users/technicians',
    byId: (id: string) => `/users/${id}`,
    update: (id: string) => `/users/${id}`,
    disable: (id: string) => `/users/${id}/disable`,
  },
  settings: {
    get: '/settings',
    update: '/settings',
    paymentMethods: '/settings/payment-methods',
    paymentMethodById: (id: string) => `/settings/payment-methods/${id}`,
    disablePaymentMethod: (id: string) => `/settings/payment-methods/${id}/disable`,
  },
  dashboard: {
    summary: '/dashboard/summary',
    analytics: '/dashboard/analytics',
    alerts: '/dashboard/alerts',
  },
} as const;
